### PR TITLE
Add new MySQL and Postgres

### PR DESCRIPTION
**Pull request by variadico**
@tw4dl @y0ssar1an @yaso195 @zquestz

### CODE REVIEW

**Comment by tw4dl** [comment]
Please provide the diff with earlier version of the scripts.

**Comment by variadico** [comment]
All of these files were mostly just minor versions bumps, like

```
url: "https://s3.amazonaws.com/apcera-sources/mysql/mysql-5.6.31.tar.gz"
url: "https://s3.amazonaws.com/apcera-sources/mysql/mysql-5.6.25.tar.gz"
```

**Comment by variadico** [comment]
Most of the time spent on this was verifying the NFS persistent still worked.

**Comment by tw4dl** [comment]
LGTM

**Comment by tw4dl** [comment]
```
➜  packages git:(add-new-dbs) ✗ diff postgres-9.4.7.conf postgres-9.4.8.conf
< name:      "postgres-9.4.7"
---
> name:      "postgres-9.4.8"
5,6c5,6
<   { url: "https://s3.amazonaws.com/apcera-sources/postgres/postgresql-9.4.7.tar.gz",
<     sha256: "737a4a39e07af589573192a794923b7f974c4acf4e4d077654d1a55852d1bfdc" },
---
>   { url: "https://s3.amazonaws.com/apcera-sources/postgres/postgresql-9.4.8.tar.gz",
>     sha256: "9558d2dda7102af12835d72a268b1f1f5c777631239b152b65c98d0218efecdf" },
13c13
<                 { package: "postgres-9.4.7" } ]
---
>                 { package: "postgres-9.4.8" } ]
15c15
< environment { "PATH": "/opt/apcera/postgres-9.4.7/bin:$PATH" }
---
> environment { "PATH": "/opt/apcera/postgres-9.4.8/bin:$PATH" }
18c18
<   export INSTALLPATH=/opt/apcera/postgres-9.4.7
---
>   export INSTALLPATH=/opt/apcera/postgres-9.4.8
25c25
<   export INSTALLPATH=/opt/apcera/postgres-9.4.7
---
>   export INSTALLPATH=/opt/apcera/postgres-9.4.8
216c216
< export INSTALLPATH=/opt/apcera/postgres-9.4.7
---
> export INSTALLPATH=/opt/apcera/postgres-9.4.8
243,244c243,244
<   tar xvzf postgresql-9.4.7.tar.gz
<   cd postgresql-9.4.7
---
>   tar xvzf postgresql-9.4.8.tar.gz
>   cd postgresql-9.4.8
```

**Comment by tw4dl** [comment]
```
➜  packages git:(add-new-dbs) ✗ diff mysql-5.6.25-apc4.conf mysql-5.6.31.conf
8c8
< # --start-cmd "sudo /opt/apcera/mysql-5.6.25/start_mysql.sh"
---
> # --start-cmd "sudo /opt/apcera/mysql-5.6.31/start_mysql.sh"
10c10
< name:      "mysql-5.6.25-apc4"
---
> name:      "mysql-5.6.31"
14,15c14,15
<   { url: "https://s3.amazonaws.com/apcera-sources/mysql/mysql-5.6.25.tar.gz",
<     sha256: "15079c0b83d33a092649cbdf402c9225bcd3f33e87388407be5cdbf1432c7fbd" },
---
>   { url: "https://s3.amazonaws.com/apcera-sources/mysql/mysql-5.6.31.tar.gz",
>     sha256: "6df1389bbf899025aee6be0f4a12b8b0135e6de7db83e3ea20201ad3633ba424" },
23c23
<                 { package: "mysql-5.6.25" } ]
---
>                 { package: "mysql-5.6.31" } ]
25c25
< environment { "PATH": "/opt/apcera/mysql-5.6.25/bin:$PATH" }
---
> environment { "PATH": "/opt/apcera/mysql-5.6.31/bin:$PATH" }
34c34
< INSTALLPATH=/opt/apcera/mysql-5.6.25
---
> INSTALLPATH=/opt/apcera/mysql-5.6.31
41c41
< # "1" means the only path that was found is: /opt/apcera/mysql-5.6.25/data
---
> # "1" means the only path that was found is: /opt/apcera/mysql-5.6.31/data
71c71
<   INSTALLPATH=/opt/apcera/mysql-5.6.25
---
>   INSTALLPATH=/opt/apcera/mysql-5.6.31
75,76c75,78
<   tar xvzf mysql-5.6.25.tar.gz
<   cd mysql-5.6.25 || exit
---
>   echo "Uncompressing MySQL source..."
>   tar xzf mysql-5.6.31.tar.gz
>   echo "Uncompressed!"
>   cd mysql-5.6.31 || exit
```

**Pull request merged**
