### PR TITLE
add mysql-5.6.25-apc3 and update node-5.10.0

### PR DESCRIPTION
**Pull request by tw4dl**
add mysql-5.6.25-apc3 with perl-5 dependency
update node-5.10.0 with node-5 provider capability

### CODE REVIEW

**Comment by johnSchnake** [comment]
LGTM, just a copy/paste from -apc2 right?

**Comment by tw4dl** [comment]
Yes, we need to figure out how to update the file instead of adding a new
file.

**Comment by lilirui** [comment]
We need bump the node package version

**Comment by lilirui** [comment]
@variadico Can you give another review?

**Comment by variadico** [comment]
> Yes, we need to figure out how to update the file instead of adding a new file.

The problem with that is that we've already shipped a node package with the same name but slightly different contents. @lloydde has been trying to get QA versioned packages to avoid ambiguity.

**Comment by variadico** [comment]
LGTM

**Pull request merged**
