### PR TITLE
WIP: Added package for NFSv4 locktests program

### PR DESCRIPTION
**Pull request by earlruby**
locktests is a C program developed by the Bull GNU/Linux NFSv4 project.

This test is aimed at stressing the fcntl locking functions.

A master process sets a lock on a file region (byte range locking). Several
slave processes try to perform operations on this region, such as: read,
write, set a new lock ... The expected results of these operations are known.
If the operation's result is the same as the expected one, the test succeeds,
otherwise it fails.

Locktests stress POSIX locks.

This is for the ENGT-4693 ticket.

cc: @bwerthmann

### CODE REVIEW

**Comment by bwerthmann** [comment]
Please upload the source tarball to the `apcera-sources` S3 bucket. Other than that, LGTM.

**Comment by bwerthmann** [comment]
The version in this package does not appear to have `-c` implemented.

```
locktests  -n 50 -f /nfs/apcfs-default/test_file -c 5
Ignoring unknown option: -c
Ignoring unknown option: 5
```
This version appears to have it included:
https://github.com/linux-test-project/ltp/blob/master/testcases/network/nfsv4/locks/locktests.c

**Comment by earlruby** [comment]
Just FYI: I'm not planning on merging this prior to LTS.

**Comment by zquestz** [comment]
LGTM once the source is in apcera-sources S3 bucket!

**Pull request closed without merging**
