### PR TITLE
Updated libpng to 1.6.19

### PR DESCRIPTION
**Pull request by zquestz**
@philpennock @rswelch

### CODE REVIEW

**Comment by rswelch** [comment]
LGTM

**Comment by zquestz** [comment]
I am building the packages now, just to confirm there are no issues. Once they are built I will supply them to SRE and click merge =)

**Comment by philpennock** [comment]
LGTM.

1. The set of changes look reasonable, I have _not_ reviewed source files to see if any other version number locations were missed.
2. I have pulled back `libpng-1.6.19.tar.gz` and `libpng-1.6.19.tar.gz.asc`; the checksum I have for the former matches that I currently see in this PR, and the detached signature verifies.

**Comment by zquestz** [comment]
NOTE: new built packages have been sent to Randy for release.

**Pull request merged**
