### PR TITLE
Fix persistence in RabbitMQ

### PR DESCRIPTION
**Pull request by earlruby**
Fix persistence in RabbitMQ.

Fixes #ENGT-7591

### CODE REVIEW

**Comment by earlruby** [comment]
@variadico

**Comment by earlruby** [comment]
@yaso195

**Comment by yaso195** [comment]
Do we need to create a new package as `apc2`? Why cant we update the existing one?

**Comment by earlruby** [comment]
Because if I upload the a package with the same name but a different SHA to S3 that will cause all current tests to break.

**Comment by yaso195** [comment]
LGTM, once the tests pass

**Comment by variadico** [comment]
Also because these are two different packages. One has persistence and the other doesn't. We need a way to tell them apart.

**Comment by variadico** [comment]
LGTM

**Comment by earlruby** [comment]
All tests pass: https://github.com/apcera/continuum/pull/5133

**Pull request merged**
