### PR TITLE
Added ubuntu 14.4.3

### PR DESCRIPTION
**Pull request by yaso195**
*Added the conf files for ubuntu-14.04.3
*Updated the README based on new packages

@variadico @earlruby

### CODE REVIEW

**Comment by earlruby** [comment]
Since this build includes all of the Ubuntu updates available on the day of the build, is there any way to include the output of `date +%Y%m%d` in the name of the package? That way, for instance, the package created today would be named `ubuntu-14.04.3-updated20160111`.

**Comment by krobertson** [comment]
Not in the package name, unless the person executing it does that. Other option could be to just add like a `date +%Y%m%d > /etc/buildtime` line within the script.

**Comment by variadico** [comment]
LGTM

**Comment by earlruby** [comment]
As long as the package name that gets checked includes the date, LGTM. I talked to @variadico and there's a `-p###` convention used for patches. Maybe we use `-uYYYYMMDD` to indicate the date updated? (e.g. The exported file would be `ubuntu-14.04.3-u20160112.cntmp` and the image name would be `ubuntu-14.04.3-u20160112`.)

**Comment by variadico** [comment]
Yeah. Let's make sure the `.cntmp` file that ends up in S3 has some sort of date tag.

**Comment by yaso195** [comment]
Done the ubuntu-14.04.3 are uploaded to `apcera-imports` bucket as `ubuntu-14.04.3-build-essential-u20160113.cntmp` and `ubuntu-14.04.3-u20160113.cntmp`

**Pull request merged**
