### PR TITLE
Add Node 4.4.6 and 5.12.0

### PR DESCRIPTION
**Pull request by variadico**
Update Node to latest security release.
https://nodejs.org/en/blog/vulnerability/june-2016-security-releases/

@lilirui @lloydde @tw4dl @vitroth @yaso195 @zquestz

### CODE REVIEW

**Comment by variadico** [comment]
4.4.5 -> 4.4.6
```diff
1c1
< name:      "node-4.4.5"
---
> name:      "node-4.4.6"
5,6c5,6
<   { url: "https://s3.amazonaws.com/apcera-sources/node/node-v4.4.5-linux-x64.tar.gz",
<     sha256: "15d57c4a3696df8d5ef1bba452d38e5d27fc3c963760eeb218533c48381e89d5" },
---
>   { url: "https://s3.amazonaws.com/apcera-sources/node/node-v4.4.6-linux-x64.tar.gz",
>     sha256: "bef5cc1db30b56d3f40b123c6a40529b6f69c403fa969ec2654b62d4cac95e26" },
14c14
<                 { runtime: "node-4.4.5" } ]
---
>                 { runtime: "node-4.4.6" } ]
16c16
< environment { "PATH": "/opt/apcera/node-4.4.5/bin:$PATH" }
---
> environment { "PATH": "/opt/apcera/node-4.4.6/bin:$PATH" }
22c22
<       export INSTALLPATH=/opt/apcera/node-4.4.5
---
>       export INSTALLPATH=/opt/apcera/node-4.4.6
27,28c27,28
<       tar xzvf node-v4.4.5-linux-x64.tar.gz
<       mv node-v4.4.5-linux-x64/* $INSTALLPATH
---
>       tar xzvf node-v4.4.6-linux-x64.tar.gz
>       mv node-v4.4.6-linux-x64/* $INSTALLPATH
```

**Comment by variadico** [comment]
5.11.1 -> 5.12.0
```diff
1c1
< name:      "node-5.11.1"
---
> name:      "node-5.12.0"
5,6c5,6
<   { url: "https://s3.amazonaws.com/apcera-sources/node/node-v5.11.1-linux-x64.tar.gz",
<     sha256: "d8e30e79a1e4ad56f55ef59facdf913c950e9664528f59f4388e85fdd899dfde" },
---
>   { url: "https://s3.amazonaws.com/apcera-sources/node/node-v5.12.0-linux-x64.tar.gz",
>     sha256: "c0f459152aa87aba8a019a95899352170db0d8d52c860715c88356cb253fe2c4" },
14c14
<                 { runtime: "node-5.11.1" } ]
---
>                 { runtime: "node-5.12.0" } ]
16c16
< environment { "PATH": "/opt/apcera/node-5.11.1/bin:$PATH" }
---
> environment { "PATH": "/opt/apcera/node-5.12.0/bin:$PATH" }
22c22
<       export INSTALLPATH=/opt/apcera/node-5.11.1
---
>       export INSTALLPATH=/opt/apcera/node-5.12.0
27,28c27,28
<       tar xzvf node-v5.11.1-linux-x64.tar.gz
<       mv node-v5.11.1-linux-x64/* $INSTALLPATH
---
>       tar xzvf node-v5.12.0-linux-x64.tar.gz
>       mv node-v5.12.0-linux-x64/* $INSTALLPATH
```

**Comment by zquestz** [comment]
LGTM

**Comment by tw4dl** [comment]
Thanks for putting in the diff. Makes review much easier.

**Comment by lilirui** [comment]
LGTM

**Comment by lloydde** [comment]
LGTM for second gate. /cc @gabrieljackson

**Pull request merged**
