### PR TITLE
Increased the build timeout for postgres packages

### PR DESCRIPTION
**Pull request by yaso195**
Postgres packages take a while to createm more than the default timeout (20sec), especially in
openstack clusters. This was causing `apcera-setup bootstrap` to fail on openstack. For that reason, timeout variable is defined in new postgres packages and set to 600.

@earlruby @variadico

### CODE REVIEW

**Comment by variadico** [comment]
Maybe we should state why this is necessary.

**Comment by variadico** [comment]
Have we tested any of this?

**Comment by yaso195** [comment]
Tested both `postgres-9.4.4-apc2` and postgres-9.4.5-apc1`

**Comment by variadico** [comment]
Cool. Now we just need to say why we need this in the PR so we have some history. :)

**Comment by variadico** [comment]
Sweet.

**Comment by variadico** [comment]
LGTM

**Comment by earlruby** [comment]
A little more background: Health Manager was checking the port for the service while Postgres was still installing. HM would see that the service wasn't running and kill the job.

Even more background: This problem appears to have affected other jobs in the past and people worked around it by adding the `--optional` flag when defining open ports for the job rather than increasing the timeout. `--optional` does not make the port optional -- it makes HM ignore the fact that there's nothing responding on the port. That means that your job starts and works, but if it the process locks up and stops servicing requests the HM doesn't notice that fact. 

I think we should change the flag from `--optional` to `--disable-port-health-check` to make it really obvious what you're doing by passing that flag.

**Comment by earlruby** [comment]
LGTM

**Comment by earlruby** [comment]
Sorry, mouse slip -- clicked the wrong button.

**Comment by yaso195** [comment]
@earlruby earlier we were using `optional` flag while creating the mysql-app, and it was causing a race condition while binding the provider to the app. We are currently not using `optional` flag for postgres app.

**Pull request merged**
