### PR TITLE
Remove non-essential files for MySQL

### PR DESCRIPTION
**Pull request by variadico**
Currently, the resulting MySQL package is a little over 1GB. This
reduces the final size by about half.

@zquestz @yaso195

### CODE REVIEW

**Comment by variadico** [comment]
Wow. So the uncompressed MySQL folder is about half as big, but the `cntmp` is only `123MB`!

Also, I just tested this with the Node todo app. Everything seems to be working great.

**Comment by yaso195** [comment]
Can you also try with example-rails-mysql and example-java-jdbc-mysql to make sure it works?

**Comment by variadico** [comment]
`example-java-jdbc-mysql` is broken because it needs `mysql-connector-java-5.1.38-bin.jar`. It's broken with both the new and old MySQL package.

**Comment by variadico** [comment]
The Ruby app is also failing with the old package... :/

**Comment by variadico** [comment]
@yaso195 We fixed the Ruby and Java apps that were failing. I think this is good to go now.

**Comment by zquestz** [comment]
Would like to see this added to the package manifest (do not remove the old copy). A branch of continuum that updates tests to use the new package, and green runs before we consider a merge.

**Comment by zquestz** [comment]
LGTM

**Pull request merged**
